In [8]:
import numpy as np

In [62]:
a = np.arange(10,71,10)
b = np.arange(1,8,1)
a, b

(array([10, 20, 30, 40, 50, 60, 70]), array([1, 2, 3, 4, 5, 6, 7]))

In [63]:
#operacje na tabelach
#dodawanie, odejmowanie, mnożenie, dodatawanie stałej macierzy
a+b, a-b, a*b, a+5, b**2

(array([11, 22, 33, 44, 55, 66, 77]),
 array([ 9, 18, 27, 36, 45, 54, 63]),
 array([ 10,  40,  90, 160, 250, 360, 490]),
 array([15, 25, 35, 45, 55, 65, 75]),
 array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32))

In [64]:
#mnożenie tabel
a*=2
a

array([ 20,  40,  60,  80, 100, 120, 140])

In [34]:
#a/=3 to nie zadzaiała ponieważ w wyniku dzielenia zmienia się typ wartości wewnątrz tablicy z int na float 
a=a/3
a.dtype

dtype('float64')

## Broadcasting tablic pythonowych:

In [67]:
#tworze tablice do przeprowadzenia bradcastowania, wyświetlam obie tablice 
arr1= np.array([[1],[2],[3]])
arr2= np.array([1, 2, 3])
arr1, arr2

(array([[1],
        [2],
        [3]]),
 array([1, 2, 3]))

In [44]:
#to jest broadcasting mówiąc prościej jest to  reshape (rozciąganie) mniejszej macierzy do większej
#możliwe jest też dociąganie obu tablic, zwrócić uwagę należy że to nie jest operator mnożenia macieżowego
#mnożone macieżowe jest zdefiniowane specjalną funkcją numpy
arr1*arr2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

## wybieranie danych z tablicy



In [23]:
np.random.seed(0)
arr = np.random.randint(-10,11,(7,8))
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [11]:
#ostatni wiersz
arr[6],arr[-1]

(array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]),
 array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]))

In [14]:
#wiersz 2 i 3, co 3 cia kolumna (slice danych)
arr[1:3, ::3]

array([[ 8,  2, -3],
       [ 7, -2,  9]])

In [16]:
#tylko wiersz pierwszy i ostatni
arr[[0,-1]]

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [17]:
#tylko wiersz ostatni a potem pierwszy
arr[[-1,0]]

array([[-10,  -6,  -5,  -4,  -2,  10,   7,   5],
       [  2,   5, -10,  -7,  -7,  -3,  -1,   9]])

In [24]:
#ostatnia kolumna
arr[:,-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [27]:
#ostatnia kolumna
arr[:,[-1]]

array([[  9],
       [  4],
       [  6],
       [  7],
       [ -1],
       [-10],
       [  5]])

In [33]:
#TRANSPOZYCJA 
arr.transpose()[-1] #pierwsza metoda
arr.T[-1] #druga metoda

array([  9,   4,   6,   7,  -1, -10,   5])

In [34]:
#numpy - indexing/slicing - doczytać

#iterowanie - tablice mają wbudowany generator więc można względem nich interować

In [40]:
for row in arr:
    print (row)
    print('='*50)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1 10  9  6]
[  9  -5   5   5 -10   8  -7   7]
[  9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10]
[-10  -6  -5  -4  -2  10   7   5]


# Porównanie wartości między python list a numpy list

In [54]:
%%timeit -r 20 -n 500 
[x**2 for x in range(1, 1001)]

298 µs ± 11 µs per loop (mean ± std. dev. of 20 runs, 500 loops each)


In [55]:
%%timeit -r 20 -n 500
np.arange(1, 1001)**2

3.59 µs ± 461 ns per loop (mean ± std. dev. of 20 runs, 500 loops each)


In [58]:
298/3.59

83.008356545961