In [1]:
import numpy as np

In [15]:
#danowe wjeściowe
numbers_list=[-20,-1,10,50,-100,100, -512, 123, 432,111,-1024]

In [16]:
# klasycznie filtrownaie danych większych od zera
[x for x in numbers_list if x>0]

[10, 50, 100, 123, 432, 111]

In [17]:
#przy użyciu numpy
arr = np.array(numbers_list)
arr>0 # okazuje się że takie wyrażenie zwracana indykator który wskazuje na którym indeksie warunekt nie został spełniony

array([False, False,  True,  True, False,  True, False,  True,  True,
        True, False])

In [18]:
arr[arr>0] # tu jest jak przefiltrować dane

array([ 10,  50, 100, 123, 432, 111])

In [20]:
arr[arr%2==0]

array([  -20,    10,    50,  -100,   100,  -512,   432, -1024])

In [26]:
#pokaż tylko >0 i jednocześnie <=100 ->trzeba stosować operatory bitowe
arr[(arr>0)&(arr<=100)]

array([ 10,  50, 100])

In [29]:
#pokaż tylko <0 i jednocześnie <100 ->trzeba stosować operatory bitowe
arr[(arr<0)|(arr>100)]

array([  -20,    -1,  -100,  -512,   123,   432,   111, -1024])

In [49]:
#tablica z NaN
tablica = np.array([-1,4,10, np.NaN, 15, 20, np.NaN]) #np.NaN - specjalna metoda do wstawiania do tablicy nan
tablica

array([-1.,  4., 10., nan, 15., 20., nan])

In [50]:
#żeby dostać wywnik filtroania trzeba zanegować wynik wyszukania realizowanego przy użyciu metody isnan 
#do negacji używamy używamy bitwise operator (znak tylda)
tablica[~np.isnan(tablica)]

array([-1.,  4., 10., 15., 20.])

In [52]:
#w numpy jest sporta grupa funkcji universal funkction (ufank) 
# np są gotowe narzędzia do obliczenia mediany, średnie, odchylenie 
tablica = tablica[~np.isnan(tablica)]
np.mean(tablica), np.median(tablica), np.std(tablica), np.min(tablica), np.max(tablica)

(9.6, 10.0, 7.49933330370107, -1.0, 20.0)